# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stopWatch.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class timer(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(733, 506)
        MainWindow.setMinimumSize(QtCore.QSize(733, 506))
        MainWindow.setMaximumSize(QtCore.QSize(733, 506))
        MainWindow.setStyleSheet("background-color: rgb(46, 52, 54);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(200, 80, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.spinBox.setFont(font)
        self.spinBox.setStyleSheet("color: rgb(211, 215, 207);")
        self.spinBox.setMaximum(23)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setGeometry(QtCore.QRect(310, 80, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setStyleSheet("color: rgb(211, 215, 207);")
        self.spinBox_2.setMaximum(59)
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_3.setGeometry(QtCore.QRect(420, 80, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.spinBox_3.setFont(font)
        self.spinBox_3.setStyleSheet("color: rgb(211, 215, 207);")
        self.spinBox_3.setMaximum(59)
        self.spinBox_3.setObjectName("spinBox_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 170, 441, 101))
        font = QtGui.QFont()
        font.setPointSize(57)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(211, 215, 207);")
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(220, 320, 281, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_2.setMinimumSize(QtCore.QSize(130, 35))
        self.pushButton_2.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    color: rgb(211, 215, 207);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 87, 83);\n"
"    color: rgb(37, 37, 37);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(130, 35))
        self.pushButton.setMaximumSize(QtCore.QSize(130, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color: rgb(211, 215, 207);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 87, 83);\n"
"    color: rgb(37, 37, 37);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 733, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.spinBox.valueChanged.connect(self.damn)
        self.spinBox_2.valueChanged.connect(self.damn)
        self.spinBox_3.valueChanged.connect(self.damn)
        
        self.timer = QtCore.QTimer(MainWindow)
        self.timer.timeout.connect(self.start)

        self.second = 0  
        self.minute = 0   
        self.hour = 0
        
    def damn(self):
        self.second = self.spinBox_3.value()  
        self.minute = self.spinBox_2.value()    
        self.hour = self.spinBox.value()

        print(f"{self.hour} : {self.minute} : {self.second}")
        self.total_second = (self.hour*60*60) + (self.minute*60) + (self.second)
        print(self.total_second)


    def start_count(self):
        self.spinBox.setDisabled(True)
        self.spinBox_2.setDisabled(True)
        self.spinBox_3.setDisabled(True)
        self.timer.start(1000)
        self.pushButton.setText(self._translate("MainWindow", "pause"))
        self.pushButton.clicked.connect(self.pause)

    def start(self):
        self.time = convert(self.total_second)
        self.label.setText(self._translate("MainWindow", self.time))
        self.total_second -= 1
        if self.total_second == 0:
            self.timer.stop()

    def pause(self):
        self.timer.stop()
        self.pushButton.setText(self._translate("MainWindow", "start"))
        self.pushButton.clicked.connect(self.start_count)

    def stop(self):
        self.total_second = 0
        self.label.setText(self._translate("MainWindow", "00:00:00"))
        self.timer.stop()
        self.pushButton.setText(self._translate("MainWindow", "start"))
        self.pushButton.clicked.connect(self.start_count)
        self.spinBox.setDisabled(False)
        self.spinBox_2.setDisabled(False)
        self.spinBox_3.setDisabled(False)

    def retranslateUi(self, MainWindow):
        self._translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(self._translate("MainWindow", "Timer"))
        self.label.setText(self._translate("MainWindow", "00:00:00"))
        self.pushButton_2.setText(self._translate("MainWindow", "stop"))
        self.pushButton.setText(self._translate("MainWindow", "start"))

        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.pushButton_2.clicked.connect(self.stop)
        self.pushButton.clicked.connect(self.start_count)

def convert(seconds): 
    seconds = seconds % (24 * 3600) 
    hour = seconds // 3600
    seconds %= 3600
    minutes = seconds // 60
    seconds %= 60
      
    return "%d:%02d:%02d" % (hour, minutes, seconds) 


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = timer()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
